name: portal_berita_indonesia
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.2.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  get_it: ^7.2.0
  hydrated_bloc: ^7.1.0
  intl: ^0.17.0
  news_repository:
    path: packages/news_repository
  path_provider: ^2.0.5
  url_launcher: ^6.0.12

dev_dependencies:
  bloc_test: ^8.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
